import 'package:flutter/material.dart';

import '../config/app_theme.dart';
import '../l10n/app_localizations.dart';
import '../l10n/localized_labels.dart';
import '../models/exchange_models.dart';
import '../services/ai_vision_service.dart';
import '../services/donation_service.dart';
import '../services/tax_receipt_pdf_service.dart';

/// A downloadable 501(c)(3) PDF receipt generated by a completed exchange.
class ExchangeReceiptCard extends StatefulWidget {
  const ExchangeReceiptCard({super.key, required this.receipt});

  final ExchangeTaxReceipt receipt;

  @override
  State<ExchangeReceiptCard> createState() => _ExchangeReceiptCardState();
}

class _ExchangeReceiptCardState extends State<ExchangeReceiptCard> {
  bool _downloading = false;

  Future<void> _download() async {
    setState(() => _downloading = true);
    final message = await TaxReceiptPdfService.instance
        .downloadExchangeReceipt(widget.receipt);
    if (!mounted) return;
    setState(() => _downloading = false);
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(message)));
  }

  @override
  Widget build(BuildContext context) {
    final loc = AppLocalizations.of(context);
    final receipt = widget.receipt;
    final asset = receipt.asset;

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                CircleAvatar(
                  backgroundColor: AppTheme.primaryBlue.withValues(alpha: 0.12),
                  child: const Icon(
                    Icons.swap_horiz,
                    color: AppTheme.primaryBlue,
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(asset.title,
                          style: Theme.of(context).textTheme.titleMedium),
                      const SizedBox(height: 4),
                      Text(
                        loc.t('exchangeReceipt.meta', {
                          'id': receipt.exchangeId,
                          'assetId': asset.assetId,
                          'category': locCategory(loc, asset.category),
                        }),
                        style: Theme.of(context).textTheme.bodySmall,
                      ),
                      const SizedBox(height: 4),
                      Text(
                        loc.t('exchangeReceipt.parties', {
                          'donor': receipt.donor.name,
                          'recipient': receipt.recipient.name,
                          'condition': locCondition(loc, asset.condition),
                        }),
                        style: Theme.of(context).textTheme.bodySmall,
                      ),
                    ],
                  ),
                ),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    Text(
                      formatUsd(asset.fairMarketValueUsd),
                      style: Theme.of(context).textTheme.titleMedium?.copyWith(
                            color: AppTheme.accentTeal,
                            fontWeight: FontWeight.bold,
                          ),
                    ),
                    Text(
                      loc.t('exchangeReceipt.fmvLabel'),
                      style: Theme.of(context).textTheme.labelSmall,
                    ),
                  ],
                ),
              ],
            ),
            const SizedBox(height: 12),
            const Divider(height: 1),
            const SizedBox(height: 12),
            Row(
              children: [
                Icon(Icons.calendar_today_outlined,
                    size: 16, color: Colors.grey.shade600),
                const SizedBox(width: 6),
                Text(
                  formatDonationDate(receipt.issuedAt),
                  style: Theme.of(context).textTheme.bodySmall,
                ),
                const Spacer(),
                Chip(
                  label: Text(receipt.receiptNumber),
                  visualDensity: VisualDensity.compact,
                ),
              ],
            ),
            const SizedBox(height: 16),
            SizedBox(
              width: double.infinity,
              child: OutlinedButton.icon(
                onPressed: _downloading ? null : _download,
                icon: _downloading
                    ? const SizedBox(
                        width: 18,
                        height: 18,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Icon(Icons.picture_as_pdf_outlined),
                label: Text(
                  _downloading
                      ? loc.t('common.generatingPdf')
                      : loc.t('exchangeReceipt.download'),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
